[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
speedrun = "52cGns3aQ3UYrbb7FTztaJXhxmbHku1TCVi4CaLsVszg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/dev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
